### ISSUE TITLE
docker pull alterway/php:5.5-apache doesn't work

### ISSUE THREAD

**Issue by terrafrost** [alterway/docker-php#3]
https://github.com/alterway/docker-php/blob/master/doc-php-apache.md implies that it should work but when I try `docker pull alterway/php:5.5-apache` I get the following:

```
Error response from daemon: manifest for alterway/php:5.5-apache not found
```

`docker pull alterway/php:5.6-apache` works as does 7.0 and 7.1 but not 5.5. If it's not going to be officially supported it should be removed the Version available section of doc-php-apache.md and from README.md.

**Comment by awdockerhub** [comment]
Hello,
Thanks for your feedback.
Versions 5.5 and 5.4 are now available on the docker hub

(Please see https://hub.docker.com/r/alterway/php/builds/ for builds status)
